package co.com.softco.model.pojos;
// Generated 9/11/2014 05:39:06 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * ModeloTracker generated by hbm2java
 */
public class ModeloTracker  implements java.io.Serializable {


     private String codTarcker;
     private String descModelo;
     private Set parametrizacionTrazas = new HashSet(0);

    public ModeloTracker() {
    }

	
    public ModeloTracker(String codTarcker, String descModelo) {
        this.codTarcker = codTarcker;
        this.descModelo = descModelo;
    }
    public ModeloTracker(String codTarcker, String descModelo, Set parametrizacionTrazas) {
       this.codTarcker = codTarcker;
       this.descModelo = descModelo;
       this.parametrizacionTrazas = parametrizacionTrazas;
    }
   
    public String getCodTarcker() {
        return this.codTarcker;
    }
    
    public void setCodTarcker(String codTarcker) {
        this.codTarcker = codTarcker;
    }
    public String getDescModelo() {
        return this.descModelo;
    }
    
    public void setDescModelo(String descModelo) {
        this.descModelo = descModelo;
    }
    public Set getParametrizacionTrazas() {
        return this.parametrizacionTrazas;
    }
    
    public void setParametrizacionTrazas(Set parametrizacionTrazas) {
        this.parametrizacionTrazas = parametrizacionTrazas;
    }




}


