package co.com.softco.model.pojos;
// Generated 9/11/2014 05:39:06 AM by Hibernate Tools 3.6.0



/**
 * ParametrizacionTraza generated by hbm2java
 */
public class ParametrizacionTraza  implements java.io.Serializable {


     private ParametrizacionTrazaId id;
     private ModeloTracker modeloTracker;
     private String descrCampo;
     private int posIni;
     private int posFin;

    public ParametrizacionTraza() {
    }

    public ParametrizacionTraza(ParametrizacionTrazaId id, ModeloTracker modeloTracker, String descrCampo, int posIni, int posFin) {
       this.id = id;
       this.modeloTracker = modeloTracker;
       this.descrCampo = descrCampo;
       this.posIni = posIni;
       this.posFin = posFin;
    }
   
    public ParametrizacionTrazaId getId() {
        return this.id;
    }
    
    public void setId(ParametrizacionTrazaId id) {
        this.id = id;
    }
    public ModeloTracker getModeloTracker() {
        return this.modeloTracker;
    }
    
    public void setModeloTracker(ModeloTracker modeloTracker) {
        this.modeloTracker = modeloTracker;
    }
    public String getDescrCampo() {
        return this.descrCampo;
    }
    
    public void setDescrCampo(String descrCampo) {
        this.descrCampo = descrCampo;
    }
    public int getPosIni() {
        return this.posIni;
    }
    
    public void setPosIni(int posIni) {
        this.posIni = posIni;
    }
    public int getPosFin() {
        return this.posFin;
    }
    
    public void setPosFin(int posFin) {
        this.posFin = posFin;
    }




}


