package co.com.softco.model.pojos;
// Generated 9/11/2014 05:39:06 AM by Hibernate Tools 3.6.0



/**
 * ParametrizacionTrazaId generated by hbm2java
 */
public class ParametrizacionTrazaId  implements java.io.Serializable {


     private String modCodTarcker;
     private int numeroCampo;

    public ParametrizacionTrazaId() {
    }

    public ParametrizacionTrazaId(String modCodTarcker, int numeroCampo) {
       this.modCodTarcker = modCodTarcker;
       this.numeroCampo = numeroCampo;
    }
   
    public String getModCodTarcker() {
        return this.modCodTarcker;
    }
    
    public void setModCodTarcker(String modCodTarcker) {
        this.modCodTarcker = modCodTarcker;
    }
    public int getNumeroCampo() {
        return this.numeroCampo;
    }
    
    public void setNumeroCampo(int numeroCampo) {
        this.numeroCampo = numeroCampo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ParametrizacionTrazaId) ) return false;
		 ParametrizacionTrazaId castOther = ( ParametrizacionTrazaId ) other; 
         
		 return ( (this.getModCodTarcker()==castOther.getModCodTarcker()) || ( this.getModCodTarcker()!=null && castOther.getModCodTarcker()!=null && this.getModCodTarcker().equals(castOther.getModCodTarcker()) ) )
 && (this.getNumeroCampo()==castOther.getNumeroCampo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getModCodTarcker() == null ? 0 : this.getModCodTarcker().hashCode() );
         result = 37 * result + this.getNumeroCampo();
         return result;
   }   


}


